// Константы. Перенести все сюда при рефакторинге (КАПСОМ)

const MAX_COMMENTS_NUMBER = 50;
const MAX_START_VISIBLE_COMMENTS_NUMBER = 5;
const UPLOAD_COMMENTS_NUMBER = 5;

const USER_PHOTOS_COUNT = 25;

export { MAX_COMMENTS_NUMBER, USER_PHOTOS_COUNT, MAX_START_VISIBLE_COMMENTS_NUMBER, UPLOAD_COMMENTS_NUMBER };
